<?php

$settings["title"] = "Furkan AYGUR";
$settings["description"] = "furkanaygur";
$settings["keywords"] = "furkan, aygur";
$settings["theme"] = "theme1";
$settings["search_placeholder"] = "Search Something";
$settings["welcome_title"] = "Welcome to the site";
$settings["welcome_text"] = "Welcome to the Furkan's site";
$settings["footer_about"] = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, iste!";
$settings["soical_facebook"] = "";
$settings["soical_facebook_name"] = "";
$settings["soical_twitter"] = "";
$settings["soical_twitter_name"] = "";
$settings["soical_instagram"] = "";
$settings["soical_instagram_name"] = "";
$settings["soical_github"] = "https://github.com/furkanaygur";
$settings["soical_github_name"] = "furkanaygur";
$settings["soical_linkedin"] = "https://www.linkedin.com/in/furkanaygur/";
$settings["soical_linkedin_name"] = "furkanaygur";
$settings["mainteance"] = "1";
$settings["mainteance_title"] = "";
$settings["mainteance_description"] = "";
$settings["smtp_host"] = "smtp.gmail.com";
$settings["smtp_email"] = "yourmail@mail.com";
$settings["smtp_password"] = "yourpassword";
$settings["smtp_sender_name"] = "Furkan Aygur";
$settings["smtp_secure"] = "tls";
$settings["smtp_port"] = "587";
